//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArithmeticTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArithmeticTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only add numbers between {0} and {1}..
        /// </summary>
        internal static string AdditionArgumentsOutOfRange {
            get {
                return ResourceManager.GetString("AdditionArgumentsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a number!.
        /// </summary>
        internal static string AnswerNotANumberMessage {
            get {
                return ResourceManager.GetString("AnswerNotANumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of questions must be an integer above 0..
        /// </summary>
        internal static string ArgumentMustBeAboveZero {
            get {
                return ResourceManager.GetString("ArgumentMustBeAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct!.
        /// </summary>
        internal static string CorrectAnswerMessage {
            get {
                return ResourceManager.GetString("CorrectAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string CorrectLabel {
            get {
                return ResourceManager.GetString("CorrectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only use dividends between {0} and {1}..
        /// </summary>
        internal static string DividendArgumentsOutOfRange {
            get {
                return ResourceManager.GetString("DividendArgumentsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only use divisors between {0} and {1}..
        /// </summary>
        internal static string DivisorArgumentOutOfRange {
            get {
                return ResourceManager.GetString("DivisorArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load answers table: {0}.
        /// </summary>
        internal static string ErrorLoadingAnswersTable {
            get {
                return ResourceManager.GetString("ErrorLoadingAnswersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        internal static string ExcellentGrade {
            get {
                return ResourceManager.GetString("ExcellentGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string GoodGrade {
            get {
                return ResourceManager.GetString("GoodGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesses.
        /// </summary>
        internal static string GuessesLabel {
            get {
                return ResourceManager.GetString("GuessesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect, you are {0} away!.
        /// </summary>
        internal static string IncorrectGuessMessage {
            get {
                return ResourceManager.GetString("IncorrectGuessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect, it was {0}.
        /// </summary>
        internal static string IncorrectThirdGuessMessage {
            get {
                return ResourceManager.GetString("IncorrectThirdGuessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of guesses for this question: {0}..
        /// </summary>
        internal static string InvalidNumberOfGuesses {
            get {
                return ResourceManager.GetString("InvalidNumberOfGuesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic Tester.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only multiply numbers between {0} and {1}..
        /// </summary>
        internal static string MultiplicationArgumentsOutOfRange {
            get {
                return ResourceManager.GetString("MultiplicationArgumentsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding.
        /// </summary>
        internal static string OutstandingGrade {
            get {
                return ResourceManager.GetString("OutstandingGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QuestionLabel {
            get {
                return ResourceManager.GetString("QuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfactory.
        /// </summary>
        internal static string SatisfactoryGrade {
            get {
                return ResourceManager.GetString("SatisfactoryGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only subtract numbers between {0} and {1}..
        /// </summary>
        internal static string SubtractionArgumentsOutOfRange {
            get {
                return ResourceManager.GetString("SubtractionArgumentsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed the test.
        /// </summary>
        internal static string TestCompleteMessage {
            get {
                return ResourceManager.GetString("TestCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Arithmetic Operator..
        /// </summary>
        internal static string UnknownOperatorException {
            get {
                return ResourceManager.GetString("UnknownOperatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see your teacher.
        /// </summary>
        internal static string UnsatisfactoryGrade {
            get {
                return ResourceManager.GetString("UnsatisfactoryGrade", resourceCulture);
            }
        }
    }
}
